// AKTUELL
<ConfigScreen>:
    orientation: 'vertical'
    padding: 10
    spacing: 20 

    
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(50)

        Label:
            text: 'MQTT-Host'
            size_hint_x: 0.2

        TextInput:
            id: mqtt_host_input
            size_hint_x: 0.4
            multiline: False
            

        Label:
            text: 'Port'
            size_hint_x: 0.1
            
        TextInput:
            id: port_input
            size_hint_x: 0.3
            multiline: False
        
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(50)

        Label:
            text: "User Name"
            size_hint_x: 0.2
        TextInput:
            id: username_input
            size_hint_x: 0.4
            multiline: False
            

        Label:
            text: 'Password'
            size_hint_x: 0.1
        TextInput:
            id: password_input
            size_hint_x: 0.3
            multiline: False
        
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(50)

        Label:
            text: "Full Topic"
            size_hint_x: 0.2
        TextInput:
            id: full_topic_input
            size_hint_x: 0.8
            multiline: False

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(50)

        Label:
            text: 'Intervals'
            size_hint_x: 0.2
        Spinner:
            id: intervals_spinner
            text: "Select Interval"
            values: ["2sec","5sec","10sec"]
           

        Label:
            text: 'Dimensions'
            size_hint_x: 0.2
        Spinner:
            id: dimensions_spinner
            text: "Select Dimension"
            values: ['1D','2D','3D']
          

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(50)

        Button:
            text: "Check Connection"
            on_press: root.btn_checkConnection()
            size_hint_x: 0.3

        Button:
            text: 'Go'
            on_press: root.btn_go()
            size_hint_x: 0.3

        Button:
            text: 'Back'
            on_press: 
                root.btn_back()
                root.manager.transition.direction = 'right'
            size_hint_x: 0.4












// OLD
<ConfigScreen>:
    orientation: 'vertical'
    padding: 10
    spacing: 20

    GridLayout:
        cols: 4
        size_hint_y: None
        height: dp(50)

        Label:
            text: 'MQTT-Host'
            size_hint_x: 0.2

        TextInput:
            id: mqtt_host_input
            size_hint_x: 0.4
            multiline: False

        Label:
            text: 'Port'
            size_hint_x: 0.1
            
        TextInput:
            id: port_input
            size_hint_x: 0.3
            multiline: False

    GridLayout:
        cols: 4
        size_hint_y: None
        height: dp(50)

        Label:
            text: "User Name"
            size_hint_x: 0.2

        TextInput:
            id: username_input
            size_hint_x: 0.4
            multiline: False

        Label:
            text: 'Password'
            size_hint_x: 0.1

        TextInput:
            id: password_input
            size_hint_x: 0.3
            multiline: False

    GridLayout:
        cols: 2
        size_hint_y: None
        height: dp(50)

        Label:
            text: "Full Topic"
            size_hint_x: 0.2

        TextInput:
            id: full_topic_input
            size_hint_x: 0.8
            multiline: False

    GridLayout:
        cols: 4
        size_hint_y: None
        height: dp(50)

        Label:
            text: 'Intervals'
            size_hint_x: 0.2

        Spinner:
            id: intervals_spinner
            text: "Select Interval"
            values: ["2sec","5sec","10sec"]

        Label:
            text: 'Dimensions'
            size_hint_x: 0.2

        Spinner:
            id: dimensions_spinner
            text: "Select Dimension"
            values: ['1D','2D','3D']

    GridLayout:
        cols: 3
        size_hint_y: None
        height: dp(50)

        Button:
            text: "Check Connection"
            on_press: root.btn_checkConnection()
            size_hint_x: 0.3

        Button:
            text: 'Go'
            on_press: root.btn_go()
            size_hint_x: 0.3

        Button:
            text: 'Back'
            on_press: root.btn_back()
            size_hint_x: 0.4
