<MyLabel@Label>:
    size_hint_y: None
    height: dp(56)
    text: str(root.index)

<CircleMAX@BoxLayout>:
    size: 100, 100
    canvas.before:
        Color:
            rgba:1,1,1,1
        Ellipse:
            pos: self.pos     # Position of the circle (same as the widget's position)

            size: 100, 100

<MyWidget>:
    BoxLayout:
        
        orientation:"horizontal"
        FloatLayout:
            size_hint_y:0.9
            CircleMAX:
                size_hint: None, None
                pos_hint: {'center_x': root.xval, 'center_y': 0.5}
        BoxLayout:
            size_hint_y:0.3
            Button:
                text:"left"
                on_press:root.xval = root.xval + 0.1
            Button:
                text:"right"
                on_press:root.xval = root.xval - 0.1


