
<CircleMAX@BoxLayout>:
    size: 100, 100
    canvas.before:
        Color:
            rgba:1,1,1,1
        Ellipse:
            pos: self.pos     # Position of the circle (same as the widget's position)

            size: 100, 100

<MyWidget>:
    BoxLayout:
        
        orientation:"vertical"
        FloatLayout:
            size_hint_y:0.9
            CircleMAX:
                size_hint: None, None
                pos_hint: {'center_x': root.xval, 'center_y': 0.5}
        

